In [1]:
import numpy as np

In [8]:
# 1차원 배열 
arr = np.array([1,2,3])
print(arr)

# 2차원 배열 
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [10]:
print(type([1,2,3]))
type(arr)

<class 'list'>


numpy.ndarray

In [12]:
tpl = (4,5,6)
arr = np.array(tpl)
print(arr)
type(arr)

[4 5 6]


numpy.ndarray

In [15]:
lst = [1,2,3]
arr = np.array(lst)
print(arr)
type(arr)

lst2 = [[1,3,3],
        [4,5,6]]
arr2 = np.array(lst2)
print(arr2)

[1 2 3]
[[1 3 3]
 [4 5 6]]


In [ ]:
# shape 배열의 형태 
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3],[4,5,6]])

print(arr1.shape,arr2.shape)

# ndim
print(arr1.ndim, arr2.ndim)

# size 원소갯수가 나옴
print(arr1.size, arr2.size)

(3,) (2, 3)
1 2
3 6
